services:
 app:
  container_name: s3
  build:
    context: .
  ports:
    - "8080:8080"
  environment:
    AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
